services:
  - type: web
    name: student-management-backend
    runtime: java

    rootDir: backend

    buildCommand: "./mvnw clean package -DskipTests"

    startCommand: "java -jar target/*.jar"

    envVars:
      - key: DB_URL
        sync: false

      - key: DB_USERNAME
        sync: false

      - key: DB_PASSWORD
        sync: false

      - key: PORT
        value: "8081"