services:
  - type: web
    name: student-management-backend

    env: docker

    rootDir: backend

    dockerfilePath: ./Dockerfile

    envVars:
      - key: DB_URL
        sync: false

      - key: DB_USERNAME
        sync: false

      - key: DB_PASSWORD
        sync: false

      - key: PORT
        value: "8080"